AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Admin Control Microservice

Parameters:
  ProfileDataTableName:
    Type: String
    Description: Name of the profileData DynamoDB table
  ApiGatewayId:
    Type: String
    Description: ID of the shared API Gateway

Resources:
  AdminControlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          TABLE_NAME: !Ref ProfileDataTableName
      Events:
        ListUsersApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayId
            Path: /admin-control/users
            Method: GET
        GetUserApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayId
            Path: /admin-control/users/{user_id}
            Method: GET
        AddUserApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayId
            Path: /admin-control/users
            Method: POST
        DeleteUserApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayId
            Path: /admin-control/users/{user_id}
            Method: DELETE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfileDataTableName

Outputs:
  AdminControlApiUrl:
    Description: API Gateway endpoint URL for Admin Control Service
    Value: !Sub 'https://${ApiGatewayId}.execute-api.${AWS::Region}.amazonaws.com/Prod/admin-control/users'
