AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: User Profile Microservice

Parameters:
  ProfileDataTableName:
    Type: String
    Description: Name of the profileData DynamoDB table
  ApiGatewayId:
    Type: String
    Description: ID of the shared API Gateway

Resources:
  UserProfileFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: UserProfileDynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:PutItem
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ProfileDataTableName}"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  UserProfileFunctionGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: app.lambda_handler
      Runtime: nodejs14.x
      Environment:
        Variables:
          TABLE_NAME: !Ref ProfileDataTableName
      Role: !GetAtt UserProfileFunctionRole.Arn
      Events:
        GetUserProfile:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayId
            Path: /user-profile
            Method: GET

  UserProfileFunctionSet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: app.lambda_handler_setProfile
      Runtime: nodejs14.x
      Environment:
        Variables:
          TABLE_NAME: !Ref ProfileDataTableName
      Role: !GetAtt UserProfileFunctionRole.Arn
      Events:
        SetUserProfile:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayId
            Path: /user-profile
            Method: POST

Outputs:
  UserProfileApiUrl:
    Description: API Gateway endpoint URL for User Profile Service
    Value: !Sub 'https://${ApiGatewayId}.execute-api.${AWS::Region}.amazonaws.com/Prod/user-profile'
