AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: User Profile Microservice

Parameters:
  ProfileDataTableName
    Type: String
    Description: Name of the profileData DynamoDB table
  ApiGatewayId:
    Type: String
    Description: ID of the shared API Gateway

Resources:
  UserProfileFunctionGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: app.lambda_handler
      Runtime: nodejs14.x
      Environment:
        Variables:
          TABLE_NAME: !Ref ProfileDataTableName
      Events:
        GetUserProfile:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayId
            Path: /user-profile
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProfileDataTableName

  UserProfileFunctionSet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/
      Handler: app.lambda_handler_setProfile
      Runtime: nodejs14.x
      Environment:
        Variables:
          TABLE_NAME: !Ref ProfileDataTableName
      Events:
        SetUserProfile:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayId
            Path: /user-profile
            Method: POST
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref ProfileDataTableName

Outputs:
  UserProfileApiUrl:
    Description: API Gateway endpoint URL for User Profile Service
    Value: !Sub 'https://${ApiGatewayId}.execute-api.${AWS::Region}.amazonaws.com/Prod/user-profile'
