AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for API Gateway with multiple microservices using DynamoDB.

Globals:
  Function:
    Timeout: 560
    MemorySize: 3008
    Runtime: python3.10

Resources:
  # Admin Control Service
  AdminControlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AdminControlTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  AdminControlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../microservices/Admin-Control/
      Handler: app.lambda_handler
      Environment:
        Variables:
          AWS_ENDPOINT: http://localhost:4566  
          TABLE_NAME: AdminControlTable
      Events:
        AdminControlApi:
          Type: Api
          Properties:
            Path: /admin-control
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: AdminControlTable

  # Authentication Service
  AuthenticationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AuthenticationTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  AuthenticationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../microservices/Authentication/
      Handler: app.lambda_handler
      Environment:
        Variables:
          AWS_ENDPOINT: http://localhost:4566
          TABLE_NAME: AuthenticationTable
      Events:
        AuthenticationApi:
          Type: Api
          Properties:
            Path: /authentication
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: AuthenticationTable

  # Notifications Service
  NotificationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: NotificationsTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  NotificationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../microservices/Notifications/
      Handler: app.lambda_handler
      Environment:
        Variables:
          AWS_ENDPOINT: http://localhost:4566
          TABLE_NAME: NotificationsTable
      Events:
        NotificationsApi:
          Type: Api
          Properties:
            Path: /notifications
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: NotificationsTable

  # Transaction Data Analysis Service
  TransDataAnalysisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TransDataAnalysisTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  TransDataAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../microservices/Trans-DataAnalysis/
      Handler: app.lambda_handler
      Environment:
        Variables:
          AWS_ENDPOINT: http://localhost:4566
          TABLE_NAME: TransDataAnalysisTable
      Events:
        TransDataAnalysisApi:
          Type: Api
          Properties:
            Path: /trans-dataanalysis
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TransDataAnalysisTable

  # User Profile Service
  UserProfileTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserProfileTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  UserProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../microservices/User-Profile/
      Handler: app.lambda_handler
      Environment:
        Variables:
          AWS_ENDPOINT: http://localhost:4566
          TABLE_NAME: UserProfileTable
      Events:
        UserProfileApi:
          Type: Api
          Properties:
            Path: /user-profile
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: UserProfileTable
