AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Shared Infrastructure DB
Resources:
  TransDataAnalysisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: transactionData
      AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      - AttributeName: sk
        AttributeType: S
      - AttributeName: expenseName
        AttributeType: S
      KeySchema:
      - AttributeName: pk
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      GlobalSecondaryIndexes:
      - IndexName: ExpenseNameIndex
        KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: expenseName
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      Tags:
      - Key: Environment
        Value: Production
    Metadata:
      SamResourceId: TransDataAnalysisTable
  UserDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: profileData
      AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      KeySchema:
      - AttributeName: pk
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      Tags:
      - Key: Environment
        Value: Production
    Metadata:
      SamResourceId: UserDataTable
Outputs:
  ProfileDataTableName:
    Description: Name of the profileData DynamoDB table
    Value:
      Ref: UserDataTable
  TransactionTableName:
    Description: Name of the transactionData DynamoDB table
    Value:
      Ref: TransDataAnalysisTable
