AWSTemplateFormatVersion: '2010-09-09'
Description: Main Infrastructure Stack - DynamoDB Tables

Resources:
  # DynamoDB Table for Transaction Data
  TransDataAnalysisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: transactionData
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: expenseName
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      GlobalSecondaryIndexes:
        - IndexName: ExpenseNameIndex
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: expenseName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: Production

  # DynamoDB Table for User Data
  UserDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: profileData
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: Production

Outputs:
  ProfileDataTableName:
    Description: "Name of the profileData DynamoDB table"
    Value: !Ref UserDataTable

  TransactionDataTableName:
    Description: "Name of the transactionData DynamoDB table"
    Value: !Ref TransDataAnalysisTable
