name: CI Pipeline for Expo App

on:
  push:
    branches:
      - dev      # Trigger on pushes to the 'dev' branch
  pull_request:
    branches:
      - stage    # Trigger on pull requests to 'stage' and 'main'
      - main

jobs:
  font-end_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

