name: CI Unit Tests

on:
  push:
    branches:
      - DeploymentMain      


jobs:
  admin-control-tests:
    name: Admin-Control Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: microservices/Admin-Control/src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: microservices/Admin-Control/src
        run: |
          python -m unittest discover -s . -p 'test_*.py'

  trans-dataanalysis-tests:
    name: Trans-DataAnalysis Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - database
          - plaid/create_link_token
          - plaid/get_access_token
          - plaid/get_transactions
          - plaid/webhook

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies
        working-directory: microservices/Trans-DataAnalysis/src/${{ matrix.service }}
        run: npm install

      - name: Run tests
        working-directory: microservices/Trans-DataAnalysis/src/${{ matrix.service }}
        run: npm test

  user-profile-tests:
    name: User-Profile Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies
        working-directory: microservices/User-Profile/src
        run: npm install

      - name: Run tests
        working-directory: microservices/User-Profile/src
        run: npm test